---
# Role: my.prometheus_stack

# Docker
# docker_user_name:
docker_network_name: monitoring

# Blackbox Exporter
blackbox_exporter:
  version: 0.21.1
  port: 9115
  additional_command_args: ''
  config_dir: etc/blackbox-exporter

# SNMP Exporter
snmp_exporter:
  version: 0.20.0
  port: 9116
  additional_command_args: ''
  config_dir: etc/snmp-exporter

# Quotes Exporter
twelvedata_exporter:
  version: main
  port: 9341
  additional_command_args: ''
  config_dir: etc/twelvedata-exporter

# JSON Exporter
json_exporter:
  version: 0.5.0
  port: 7979
  additional_command_args: ''
  config_dir: etc/json-exporter

json_exporter_python:
  version: 3.10.5-alpine
  port: 8000
  additional_command_args: 'python -m http.server 8000 --directory /etc/json-exporter'

# Remo Exporter
remo_exporter:
  version: master
  port: 9352
  additional_command_args: ''
  config_dir: etc/remo-exporter
