---
# Role: my.prometheus_stack

- name: general | create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    mode: 0755
  with_items:
    - /{{ prometheus.config_dir }}
    - /{{ prometheus.data_dir }}
    - /{{ alertmanager.config_dir }}
    - /{{ alertmanager.data_dir }}

# - name: prometheus | docker-python
#   become: true
#   yum:
#     name: docker-python
#     state: present

- name: general | docker network
  become: true
  docker_network:
    name: "{{ docker_network_name }}"
    state: present
