---
# Role: my.prometheus_stack

- name: alertmanager | ensure alertmanager.yml exists
  stat:
    path: /{{ alertmanager.config_dir }}/alertmanager.yml
  register: alertmanager_config_file

- name: alertmanager | alertmanager configuration file
  template:
    dest: /{{ alertmanager.config_dir }}/alertmanager.yml
    force: true
    src: "{{ alertmanager.config_dir }}/alertmanager.yml.j2"
    mode: 0644
  register: alertmanager_configuration
  when: not alertmanager_config_file.stat.exists

- name: alertmanager | docker alertmanager
  docker_container:
    command: >
      --config.file=/{{ alertmanager.config_dir }}/alertmanager.yml
      --storage.path=/alertmanager
      {{ alertmanager.additional_command_args }}
    image: prom/alertmanager:{{ alertmanager.version }}
    name: alertmanager
    networks:
      - name: "{{ docker_network_name }}"
    published_ports: >-
      {{
        (alertmanager.port > 0) | ternary([(alertmanager.port | string) + ':9093'], [])
      }}
    recreate: "{{ alertmanager_configuration.changed }}"
    restart_policy: always
    state: started
    volumes:
      - /{{ alertmanager.config_dir }}/:/{{ alertmanager.config_dir }}:ro
      - /{{ alertmanager.data_dir }}:/alertmanager:rw
  register: alertmanager_container

# In certain situations if a manual change means Prometheus in Docker
# auto restarted but a host mounted file wasn't present it'll be auto
# created as a directory instead of a file.
- name: alertmanager | check docker host file mounts
  stat:
    path: /{{ alertmanager.config_dir }}/alertmanager.yml
  register: alertmanager_docker_file_mounts
