---
# Role: my.ubuntu2004_base

- name: systemd-journald | Put journald.conf
  template:
    src: "{{ systemd_journald.config_path }}.j2"
    dest: "/{{ systemd_journald.config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart_systemd_journald_service
