---
  - import_tasks: 01_general.yml

  - import_tasks: 02_database.yml
    when: drone_server_enable == "true" and drone_database_driver != "sqlite"

  - import_tasks: 03_server.yml
    when: drone_server_enable == "true"

  - import_tasks: 04_docker-runner.yml
    when: drone_docker_runner_enable == "true"

  - import_tasks: 05_ssh-runner.yml
    when: drone_ssh_runner_enable == "true"

