---
# Role: my.grafana_stack

# Docker
# docker_user_name:
docker_network_name: grafana

# Alertmanager
cortex:
  version: v1.11.0
  port: 9091
  additional_command_args: ''
  config_dir: etc/cortex
  data_dir: data/cortex

# Mimir
mimir_version: 2.0.0
mimir_port: 9009
mimir_additional_command_args: '-config.file /etc/mimir/standalone.yaml'
mimir_config_dir: etc/mimir
mimir_data_dir: data/mimir

# Grafana
grafana:
  version: latest
  port: 3000
  additional_command_args: ''
  config_dir: etc/grafana
  data_dir: data/grafana
