---
# Role: my.prometheus_exporter

- name: blackbox | ensure blackbox.yml deployed by Drone
  stat:
    path: /{{ blackbox_exporter.config_dir }}/blackbox.yml
  register: blackbox_exporter_config_file

- name: blackbox | blackbox_exporter configuration file
  template:
    dest: /{{ blackbox_exporter.config_dir }}/blackbox.yml
    force: true
    src: "{{ blackbox_exporter.config_dir }}/blackbox.yml.j2"
    mode: 0644
  register: blackbox_exporter_configuration
  when: not blackbox_exporter_config_file.stat.exists

- name: blackbox | docker blackbox_exporter
  docker_container:
    command: >
      --config.file=/{{ blackbox_exporter.config_dir }}/blackbox.yml
      {{ blackbox_exporter.additional_command_args }}
    image: prom/blackbox-exporter:v{{ blackbox_exporter.version }}
    name: blackbox_exporter
    networks:
      - name: "{{ docker_network_name }}"
    published_ports: >-
      {{
        (blackbox_exporter.port > 0) | ternary([(blackbox_exporter.port | string) + ':9115'], [])
      }}
    recreate: "{{ blackbox_exporter_configuration.changed }}"
    restart_policy: always
    state: started
    volumes:
      - /{{ blackbox_exporter.config_dir }}/:/{{ blackbox_exporter.config_dir }}:ro
      - blackbox_exporter-data:/blackbox_exporter
  register: blackbox_exporter_container

# In certain situations if a manual change means Prometheus in Docker
# auto restarted but a host mounted file wasn't present it'll be auto
# created as a directory instead of a file.
- name: blackbox | Ensure docker host file mounts
  stat:
    path: /{{ blackbox_exporter.config_dir }}/blackbox.yml
  register: blackbox_exporter_docker_file_mounts
