---
# Role: my.prometheus_exporter

- name: twelvedata | Clone umatare5/twelvedata_exporter
  git:
    repo: git@github.com:umatare5/twelvedata-exporter.git
    dest: /tmp/twelvedata-exporter
    version: "{{ twelvedata_exporter.version }}"
    accept_hostkey: yes
    force: yes

- name: twelvedata | Build twelvedata_exporter
  docker_image:
    build:
      path: /tmp/twelvedata-exporter
    name: umatare5/twelvedata-exporter
    tag: "{{ twelvedata_exporter.version }}"
    push: no
    source: build

- name: twelvedata | docker twelvedata_exporter
  docker_container:
    command: >
      {{ twelvedata_exporter.additional_command_args }}
    image: umatare5/twelvedata-exporter:{{ twelvedata_exporter.version }}
    name: twelvedata_exporter
    networks:
      - name: "{{ docker_network_name }}"
    published_ports: >-
      {{
        (twelvedata_exporter.port > 0) | ternary([(twelvedata_exporter.port | string) + ':9341'], [])
      }}
    restart_policy: always
    state: started
    volumes:
      - /{{ twelvedata_exporter.config_dir }}/:/{{ twelvedata_exporter.config_dir }}:ro
      - twelvedata_exporter-data:/twelvedata_exporter
    env:
      TWELVEDATA_API_KEY: "{{ twelvedata_exporter_api_key }}"
  register: twelvedata_exporter_container

# In certain situations if a manual change means Prometheus in Docker
# auto restarted but a host mounted file wasn't present it'll be auto
# created as a directory instead of a file.
- name: twelvedata | Ensure docker host file mounts
  stat:
    path: /{{ twelvedata_exporter.config_dir }}/twelvedata.yml
  register: twelvedata_exporter_docker_file_mounts
