---
# Role: my.prometheus_exporter

- name: json | json_exporter configuration file
  template:
    dest: /{{ json_exporter.config_dir }}/json.yml
    force: true
    src: "{{ json_exporter.config_dir }}/json.yml.j2"
    mode: 0644
  register: json_exporter_configuration

- name: json | docker json_exporter
  docker_container:
    command: >
      --config.file=/{{ json_exporter.config_dir }}/json.yml
      {{ json_exporter.additional_command_args }}
    image: quay.io/prometheuscommunity/json-exporter:v{{ json_exporter.version }}
    name: json_exporter
    networks:
      - name: "{{ docker_network_name }}"
    published_ports: >-
      {{
        (json_exporter.port > 0) | ternary([(json_exporter.port | string) + ':7979'], [])
      }}
    recreate: "{{ json_exporter_configuration.changed }}"
    restart_policy: always
    state: started
    volumes:
      - /{{ json_exporter.config_dir }}/:/{{ json_exporter.config_dir }}:ro
      - json_exporter-data:/json_exporter
  register: json_exporter_container

# In certain situations if a manual change means Prometheus in Docker
# auto restarted but a host mounted file wasn't present it'll be auto
# created as a directory instead of a file.
- name: json | Ensure docker host file mounts
  stat:
    path: /{{ json_exporter.config_dir }}/json.yml
  register: json_exporter_docker_file_mounts
